apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: stikjgx4w-go
  janus-idp.io/tekton: stikjgx4w-go
  backstage.io/kubernetes-id: stikjgx4w-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: stikjgx4w-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
